apiVersion: apps/v1

kind: Deployment

metadata:

  name: django-app

spec:

  replicas: 1

  selector:

    matchLabels:

      app: django

  template:

    metadata:

      labels:

        app: django

    spec:

      containers:

      - name: django

        image: my-django-app-with-prom:latest

        imagePullPolicy: Never

        ports:

        - containerPort: 8000

---

apiVersion: v1

kind: Service

metadata:

  name: django-service

spec:

  type: NodePort

  selector:

    app: django

  ports:

  - port: 80

    targetPort: 8000

    nodePort: 30001