apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: preview-environment-set
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: HishamShokry
        repo: DevSecOps_Test_Project
  template:
    metadata:
      name: '{{.branch}}'  # Application name based on the branch
      namespace: 'argocd'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/HishamShokry/DevSecOps_Test_Project'
        targetRevision: '{{.head_sha}}'  # Use the PR head commit SHA
        path: 'django-app'  # Correct path to your repository's django-app directory
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.branch}}'  # Namespace based on the branch
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

