appName: django
replicaCount: 1

image:
  repository: django-app
  tag: latest
  pullPolicy: Never

containerPort: 8000

service:
  type: NodePort
  port: 80
  nodePort: 30001

# serviceAccount:
#   create: true
#   name: ""



# ingress:
# enabled: false
# annotations: {}
# hosts:
#   - host: django-app.local
#     path: /
#     pathType: ImplementationSpecific
# tls: []